name: afk_redeem
description: An app for your AFK Arena redemption codes

publish_to: 'none'

version: 1.3.0+10

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.7
  intl: ^0.19.0
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.6
  dio: ^5.5.0+1
  dio_cookie_manager: ^3.1.1
  animated_text_kit: ^4.2.1
  bubble: ^1.2.1
  package_info_plus: ^8.0.2
  flutter_animation_progress_bar: ^2.0.1
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  firebase_analytics: ^11.2.1
  firebase_crashlytics: ^4.0.4
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/gifts/
    - images/gifts/hours/
    - images/celestial/
    - images/hypogean/
    - images/christmas/
    - images/game_screenshots/
