#org.gradle.jvmargs=-Xmx1536M
# Mémoire pour le daemon Gradle (Adapter si tu as peu de RAM)
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8

# Optionnel: parallélisme
org.gradle.parallel=true
org.gradle.workers.max=4

android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false
kotlin.jvm.target.validation.mode = IGNORE
